version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network
  webserver:
    image: pranit007/gofood-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/my_database
    networks:
      - mern-network
  frontend:
    image: pranit007/todo-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - mern-network
    links:
      - webserver

networks:
  mern-network:
volumes:
  mern-volume: